platform :ios, '8.0'

pod 'AFNetworking', '~> 2.0'
pod 'FXForms', '~> 1.2'
pod 'MSDynamicsDrawerViewController', '~> 1.5'
pod 'RATreeView', '~> 1.0'
pod 'STTwitter', '~> 0.2'
pod 'FontAwesomeKit', '~> 2.2'
#pod 'MDCFocusView', '~> 0.1'
#pod 'SWRevealViewController', '~> 2.3'
pod 'M13ProgressSuite', '~> 1.2'
pod 'KGModal', '~> 1.1'
pod 'Parse', '~> 1.7'
pod 'NSObject-ObjectMap', '~> 2.3'
pod 'CMPopTipView', '~> 2.2'
pod 'M13PDFKit', '1.0.2'
#pod 'vfrReader', '~> 2.7'
#pod 'ReaderFramework', '~> 1.1'
#workspace 'ahaactioncenter'
#pod 'AFQuickLookView', '~> 0.3'
pod 'AMPPreviewController', '~> 0.3'
pod 'STTweetLabel', '~> 3.1'
